default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

development:
  <<: *default
  database: <%= ENV['DATABASE_DEVELOPMENT'] || 'to_do_dev' %>

test:
  <<: *default
  database: <%= ENV['DATABASE_TEST'] || 'to_do_test' %>

production:
  <<: *default
  database: <%= ENV['DATABASE_PRODUCTION'] || 'to_do_prod' %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
