default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: taiman
  password: banani123
  host: localhost

development:
  <<: *default
  database: to_do_dev

test:
  <<: *default
  database: to_do_test

production:
  <<: *default
  database: to_do_prod
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
